import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/layouts/Header";

export const metadata: Metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="bg-teal-50">
        <Header />
        {children}
      </body>
    </html>
  );
}
